package com.pointlessapps.filman.data.scraper.extractors

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.ServiceList

import org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException

internal object YoutubeExtractor : EmbedExtractor {
    override suspend fun extractVideo(embedUrl: String): List<ExtractedVideo> =
        withContext(Dispatchers.IO) {
            try {
                val service = ServiceList.YouTube
                val streamExtractor = service.getStreamExtractor(embedUrl)

                try {
                    streamExtractor.fetchPage()
                } catch (e: ContentNotAvailableException) {
                    if (e.message?.contains("reload") == true) {
                        streamExtractor.fetchPage()
                    } else {
                        throw e
                    }
                }

                val subtitles = streamExtractor.subtitlesDefault.map { subtitle ->
                    Subtitle(
                        url = subtitle.content,
                        label = subtitle.displayLanguageName + if (subtitle.isAutoGenerated) " (Auto)" else "",
                        language = subtitle.languageTag,
                    )
                }

                streamExtractor.videoStreams.sortedByDescending { it.height }.map { stream ->
                    ExtractedVideo(
                        url = stream.content,
                        serverName = "YouTube",
                        quality = "${stream.height}p",
                        isWebView = false,
                        subtitles = subtitles,
                    )
                }
            } catch (e: Exception) {
                e.printStackTrace()
                emptyList()
            }
        }
}
