package com.pointlessapps.filman.data.scraper.extractors

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException

internal object YoutubeExtractor : EmbedExtractor {
    override suspend fun extractVideo(embedUrl: String): List<ExtractedVideo> =
        withContext(Dispatchers.IO) {
            try {
                val service = ServiceList.YouTube
                val streamExtractor = service.getStreamExtractor(embedUrl)

                try {
                    streamExtractor.fetchPage()
                } catch (e: ContentNotAvailableException) {
                    if (e.message?.contains("reload") == true) {
                        streamExtractor.fetchPage()
                    } else {
                        throw e
                    }
                }

                val subtitles = try {
                    streamExtractor.subtitlesDefault.map { subtitle ->
                        Subtitle(
                            url = subtitle.content,
                            label = subtitle.displayLanguageName + if (subtitle.isAutoGenerated) {
                                " (Auto)"
                            } else {
                                ""
                            },
                            language = subtitle.languageTag,
                        )
                    }
                } catch (e: Exception) {
                    emptyList()
                }

                val audioStream = try {
                    streamExtractor.audioStreams.maxByOrNull {
                        it.averageBitrate
                    }?.content
                } catch (e: Exception) {
                    null
                }
                val videoOnly = try {
                    streamExtractor.videoOnlyStreams.sortedByDescending {
                        it.resolution.replace(Regex("0p\\d+$"), "1")
                            .replace(Regex("[^0-9]"), "")
                            .toIntOrNull() ?: 0
                    }.map { stream ->
                        ExtractedVideo(
                            url = stream.content,
                            audioUrl = audioStream,
                            serverName = "YouTube",
                            quality = stream.resolution,
                            isWebView = false,
                            subtitles = subtitles,
                        )
                    }
                } catch (e: Exception) {
                    emptyList()
                }

                val mixed = try {
                    streamExtractor.videoStreams.sortedByDescending {
                        it.resolution.replace(Regex("0p\\d+$"), "1")
                            .replace(Regex("[^0-9]"), "")
                            .toIntOrNull() ?: 0
                    }.map { stream ->
                        ExtractedVideo(
                            url = stream.content,
                            audioUrl = null,
                            serverName = "YouTube",
                            quality = stream.resolution,
                            isWebView = false,
                            subtitles = subtitles,
                        )
                    }
                } catch (e: Exception) {
                    emptyList()
                }

                (videoOnly + mixed).distinctBy { it.quality }
            } catch (e: Exception) {
                e.printStackTrace()
                emptyList()
            }
        }
}
